title: Dev Blog by jgoodman8
description: > # this means to ignore newlines until "baseurl:"
  A blog of short posts about AI, crypto, music... guided by rubber ducks for humans. An small contribution to the
  open community. Stay tuned with the updates and enjoy the music pills.
permalink: ':title/'
baseurl: "/dev-blog" # the subpath of your site
url: "" # the base hostname & protocol for your site

# Author Settings
author: Javier Guzmán # add your name
author-img: profile-pic.jpg # add your photo
about-author: AI enthusiast, ML skills and FullStack capabilities. # add description

# Disqus
discus-identifier: https-jgoodman8-github-io # add your discus identifier

# Tracker
analytics: UA-125589531-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
