title: Dev Blog by jgoodman8
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/dev-blog" # the subpath of your site
url: "" # the base hostname & protocol for your site

# Author Settings
author: Javier Guzmán # add your name
author-img: profile-pic.jpg # add your photo
about-author: AI enthusiast, ML skills and FullStack capabilities. # add description

# Disqus
discus-identifier: https-jgoodman8-github-io # add your discus identifier

# Tracker
analytics: UA-125589531-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
